CREATE DATABASE 'C:\Users\Usuario\Desktop\cSistema Comercial Java 2014\Sistema Comercial Java 2014\UMUPET.FDB' page_size 8192 user 'SYSDBA' password 'masterkey';

CREATE TABLE PRODUCAO (
  COD_PRODUCAO INTEGER  NOT NULL  ,
  DESCRICAO VARCHAR(100)  NOT NULL  ,
  STATUS_PRODUCAO CHAR(1)  NOT NULL  ,
  DATA_CADASTRO DATE  NOT NULL    ,
PRIMARY KEY(COD_PRODUCAO));





CREATE TABLE PRODUTO (
  COD_PRODUTO INTEGER  NOT NULL  ,
  NOME_PRODUTO VARCHAR(50)  NOT NULL  ,
  DESCRICAO VARCHAR(2000)  NOT NULL  ,
  QUANTIDADE INTEGER  NOT NULL  ,
  QTDE_MINIMA INTEGER  NOT NULL  ,
  QTDE_REAL INTEGER  NOT NULL  ,
  PRECO_CUSTO NUMERIC  NOT NULL  ,
  PRECO_VENDA NUMERIC    ,
  DATA_CADASTRO DATE  NOT NULL  ,
  PRODUTO_ACABADO CHAR(1)  NOT NULL  ,
  MATERIA_PRIMA CHAR(1)  NOT NULL  ,
  PRECO_UNITARIO NUMERIC  NOT NULL,
PRIMARY KEY(COD_PRODUTO));



CREATE TABLE FPAGAMENTO (
  COD_FPAGAMENTO INTEGER  NOT NULL  ,
  DESCRICAO VARCHAR(100)  NOT NULL  ,
  QTDE_PARCELAS NUMERIC  NOT NULL  ,
  ENTRADA CHAR(1)    ,
  DATA_CADASTRO INTEGER  NOT NULL    ,
PRIMARY KEY(COD_FPAGAMENTO));



CREATE TABLE ESTADO (
  COD_ESTADO INTEGER  NOT NULL  ,
  NOME_ESTADO VARCHAR(50)  NOT NULL  ,
  SIGLA CHAR(2)  NOT NULL  ,
  STATUS_ESTADO CHAR(1)  NOT NULL  ,
  DATA_CADASTRO DATE  NOT NULL    ,
PRIMARY KEY(COD_ESTADO));



CREATE TABLE CHEQUE (
  COD_CHEQUE INTEGER  NOT NULL  ,
  AGENCIA INTEGER  NOT NULL  ,
  CONTA_CORRENTE INTEGER  NOT NULL  ,
  NUMERO_CHEQUE INTEGER  NOT NULL  ,
  VALOR NUMERIC  NOT NULL    ,
PRIMARY KEY(COD_CHEQUE));



CREATE TABLE CAIXA (
  COD_CAIXA INTEGER  NOT NULL  ,
  DATA_CADASTRO DATE  NOT NULL  ,
  SALDO_INICIAL NUMERIC    ,
  SALDO_FINAL NUMERIC  NOT NULL  ,
  DIFERENCA NUMERIC  NOT NULL    ,
PRIMARY KEY(COD_CAIXA));



CREATE TABLE CIDADE (
  COD_CIDADE INTEGER  NOT NULL  ,
  ESTADO_COD_ESTADO INTEGER  NOT NULL  ,
  NOME_CIDADE VARCHAR(50)  NOT NULL  ,
  STATUS_CIDADE CHAR(1)  NOT NULL  ,
  DATA_CADASTRO DATE  NOT NULL    ,
PRIMARY KEY(COD_CIDADE)  ,
  FOREIGN KEY(ESTADO_COD_ESTADO)
    REFERENCES ESTADO(COD_ESTADO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION);


CREATE INDEX CIDADE_FKIndex1 ON CIDADE (ESTADO_COD_ESTADO);



CREATE TABLE ICOMPOSICAO (
  COD_COMPOSICAO INTEGER  NOT NULL  ,
  PRODUTO_COD_PRODUTO INTEGER  NOT NULL  ,
  NOME_PRODUTO VARCHAR(50)  NOT NULL  ,
  PARTES_PRODUTO VARCHAR(50)  NOT NULL  ,
  QUANTIDADE NUMERIC  NOT NULL    ,
PRIMARY KEY(COD_COMPOSICAO)    ,
  FOREIGN KEY(PRODUTO_COD_PRODUTO)
    REFERENCES PRODUTO(COD_PRODUTO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(PRODUTO_COD_PRODUTO)
    REFERENCES PRODUTO(COD_PRODUTO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION);


CREATE INDEX ICOMPOSICAO_FKIndex2 ON ICOMPOSICAO (PRODUTO_COD_PRODUTO);



CREATE TABLE FORNECEDOR (
  COD_FORNECEDOR INTEGER  NOT NULL  ,
  FPAGAMENTO_COD_FPAGAMENTO INTEGER  NOT NULL  ,
  CIDADE_COD_CIDADE INTEGER  NOT NULL  ,
  NOME_FORNECEDOR VARCHAR(50)  NOT NULL  ,
  DATA_CONSTITIUCAO DATE  NOT NULL  ,
  FISICO_JURIDICO CHAR(1)  NOT NULL  ,
  CPF_CNPJ VARCHAR(18)  NOT NULL  ,
  ENDERECO VARCHAR(50)  NOT NULL  ,
  ENDERECO_NUMERO INTEGER  NOT NULL  ,
  ENDERECO_COMPLEMENTO VARCHAR(50)    ,
  BAIRRO VARCHAR(50)  NOT NULL  ,
  CEP VARCHAR(15)  NOT NULL  ,
  FONE VARCHAR(15)  NOT NULL  ,
  FAX VARCHAR(15)    ,
  CONTATO VARCHAR(50)    ,
  TIPO CHAR(1)  NOT NULL  ,
  STATUS_FORNECEDOR CHAR(1)  NOT NULL  ,
  DATA_CADASTRO DATE  NOT NULL    ,
PRIMARY KEY(COD_FORNECEDOR)    ,
  FOREIGN KEY(CIDADE_COD_CIDADE)
    REFERENCES CIDADE(COD_CIDADE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(FPAGAMENTO_COD_FPAGAMENTO)
    REFERENCES FPAGAMENTO(COD_FPAGAMENTO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION);


CREATE INDEX FORNECEDOR_FKIndex1 ON FORNECEDOR (CIDADE_COD_CIDADE);
CREATE INDEX FORNECEDOR_FKIndex2 ON FORNECEDOR (FPAGAMENTO_COD_FPAGAMENTO);



CREATE TABLE IPRODUCAO (
  COD_IPRODUCAO INTEGER  NOT NULL  ,
  PRODUCAO_COD_PRODUCAO INTEGER  NOT NULL  ,
  PRODUTO_COD_PRODUTO INTEGER  NOT NULL  ,
  QUANTIDADE NUMERIC  NOT NULL  ,
  DATA_CADASTRO DATE  NOT NULL    ,
PRIMARY KEY(COD_IPRODUCAO)    ,
  FOREIGN KEY(PRODUTO_COD_PRODUTO)
    REFERENCES PRODUTO(COD_PRODUTO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(PRODUCAO_COD_PRODUCAO)
    REFERENCES PRODUCAO(COD_PRODUCAO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION);


CREATE INDEX IPRODUCAO_FKIndex1 ON IPRODUCAO (PRODUTO_COD_PRODUTO);
CREATE INDEX IPRODUCAO_FKIndex2 ON IPRODUCAO (PRODUCAO_COD_PRODUCAO);



CREATE TABLE FUNCIONARIO (
  COD_FUNCIONARIO INTEGER  NOT NULL  ,
  CIDADE_COD_CIDADE INTEGER  NOT NULL  ,
  NOME_FUNCIONARIO VARCHAR(50)  NOT NULL  ,
  ESTADO_CIVIL VARCHAR(20)  NOT NULL  ,
  SEXO CHAR(1)  NOT NULL  ,
  DATA_NACIMENTO DATE  NOT NULL  ,
  CPF CHAR(14)  NOT NULL  ,
  ENDERECO VARCHAR(50)  NOT NULL  ,
  ENDERECO_NUMERO INTEGER  NOT NULL  ,
  ENDERECO_COMPLEMENTO VARCHAR(50)    ,
  BAIRRO VARCHAR(50)  NOT NULL  ,
  CEP VARCHAR(15)  NOT NULL  ,
  FONE VARCHAR(15)  NOT NULL  ,
  STATUS_FUNCIONARIO CHAR(1)  NOT NULL  ,
  DATA_CADASTRO DATE  NOT NULL  ,
  CARGO VARCHAR(50)    ,
  SALARIO_MENSAL NUMERIC      ,
PRIMARY KEY(COD_FUNCIONARIO)  ,
  FOREIGN KEY(CIDADE_COD_CIDADE)
    REFERENCES CIDADE(COD_CIDADE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION);


CREATE INDEX FUNCIONARIO_FKIndex1 ON FUNCIONARIO (CIDADE_COD_CIDADE);



CREATE TABLE CLIENTE (
  COD_CLIENTE INTEGER  NOT NULL  ,
  CIDADE_COD_CIDADE INTEGER  NOT NULL  ,
  NOME_CLIENTE VARCHAR(50)  NOT NULL  ,
  ESTADO_CIVIL VARCHAR(20)  NOT NULL  ,
  SEXO CHAR(1)  NOT NULL  ,
  DATA_NASCIMENTO DATE  NOT NULL  ,
  FISICO_JURIDICO CHAR(1)    ,
  CPF_CNPJ VARCHAR(18)  NOT NULL  ,
  ENDERECO VARCHAR(100)  NOT NULL  ,
  ENDERECO_NUMERO INTEGER  NOT NULL  ,
  ENDERECO_COMPLEMENTO VARCHAR(50)    ,
  BAIRRO VARCHAR(50)  NOT NULL  ,
  CEP VARCHAR(15)  NOT NULL  ,
  FONE VARCHAR(15)  NOT NULL  ,
  TIPO CHAR(1)  NOT NULL  ,
  STATUS_CLIENTE CHAR(1)  NOT NULL  ,
  DATA_CADASTRO DATE  NOT NULL    ,
PRIMARY KEY(COD_CLIENTE)  ,
  FOREIGN KEY(CIDADE_COD_CIDADE)
    REFERENCES CIDADE(COD_CIDADE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION);


CREATE INDEX CLIENTE_FKIndex1 ON CLIENTE (CIDADE_COD_CIDADE);



CREATE TABLE PEDIDO_COMPRA (
  COD_PC INTEGER  NOT NULL  ,
  FORNECEDOR_COD_FORNECEDOR INTEGER  NOT NULL  ,
  DESCRICAO VARCHAR(40)  NOT NULL  ,
  DATA_CADASTRO DATE  NOT NULL    ,
PRIMARY KEY(COD_PC)  ,
  FOREIGN KEY(FORNECEDOR_COD_FORNECEDOR)
    REFERENCES FORNECEDOR(COD_FORNECEDOR)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION);


CREATE INDEX PEDIDO_COMPRA_FKIndex1 ON PEDIDO_COMPRA (FORNECEDOR_COD_FORNECEDOR);



CREATE TABLE COMPRA (
  COD_COMPRA INTEGER  NOT NULL  ,
  FUNCIONARIO_COD_FUNCIONARIO INTEGER  NOT NULL  ,
  FORNECEDOR_COD_FORNECEDOR INTEGER  NOT NULL  ,
  DATA_CADASTRO DATE  NOT NULL  ,
  STATUS_COMPRA CHAR(1)  NOT NULL  ,
  TOTAL NUMERIC  NOT NULL    ,
PRIMARY KEY(COD_COMPRA)    ,
  FOREIGN KEY(FORNECEDOR_COD_FORNECEDOR)
    REFERENCES FORNECEDOR(COD_FORNECEDOR)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(FUNCIONARIO_COD_FUNCIONARIO)
    REFERENCES FUNCIONARIO(COD_FUNCIONARIO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION);


CREATE INDEX COMPRA_FKIndex1 ON COMPRA (FORNECEDOR_COD_FORNECEDOR);
CREATE INDEX COMPRA_FKIndex2 ON COMPRA (FUNCIONARIO_COD_FUNCIONARIO);



CREATE TABLE ICOMPRA (
  COD_ICOMPRA INTEGER  NOT NULL  ,
  PRODUTO_COD_PRODUTO INTEGER  NOT NULL  ,
  COMPRA_COD_COMPRA INTEGER  NOT NULL  ,
  QUANTIDADE NUMERIC  NOT NULL  ,
  VALOR_UNITARIO NUMERIC  NOT NULL  ,
  DESCONTO NUMERIC  NOT NULL    ,
PRIMARY KEY(COD_ICOMPRA)    ,
  FOREIGN KEY(COMPRA_COD_COMPRA)
    REFERENCES COMPRA(COD_COMPRA)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(PRODUTO_COD_PRODUTO)
    REFERENCES PRODUTO(COD_PRODUTO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION);


CREATE INDEX ICOMPRA_FKIndex1 ON ICOMPRA (COMPRA_COD_COMPRA);
CREATE INDEX ICOMPRA_FKIndex2 ON ICOMPRA (PRODUTO_COD_PRODUTO);



CREATE TABLE IPEDIDO_COMPRA (
  COD_IPC INTEGER  NOT NULL  ,
  PRODUTO_COD_PRODUTO INTEGER  NOT NULL  ,
  PEDIDO_COMPRA_COD_PC INTEGER  NOT NULL  ,
  QUANTIDADE NUMERIC    ,
  VALOR INTEGER      ,
PRIMARY KEY(COD_IPC)    ,
  FOREIGN KEY(PEDIDO_COMPRA_COD_PC)
    REFERENCES PEDIDO_COMPRA(COD_PC)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(PRODUTO_COD_PRODUTO)
    REFERENCES PRODUTO(COD_PRODUTO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION);


CREATE INDEX IPEDIDO_COMPRA_FKIndex1 ON IPEDIDO_COMPRA (PEDIDO_COMPRA_COD_PC);
CREATE INDEX IPEDIDO_COMPRA_FKIndex2 ON IPEDIDO_COMPRA (PRODUTO_COD_PRODUTO);



CREATE TABLE VENDA (
  COD_VENDA INTEGER  NOT NULL  ,
  FPAGAMENTO_COD_FPAGAMENTO INTEGER  NOT NULL  ,
  CLIENTE_COD_CLIENTE INTEGER  NOT NULL  ,
  FUNCIONARIO_COD_FUNCIONARIO INTEGER  NOT NULL  ,
  DATA_CADASTRO DATE  NOT NULL  ,
  STATUS_VENDA CHAR(1)  NOT NULL  ,
  TOTAL NUMERIC  NOT NULL    ,
PRIMARY KEY(COD_VENDA)      ,
  FOREIGN KEY(FUNCIONARIO_COD_FUNCIONARIO)
    REFERENCES FUNCIONARIO(COD_FUNCIONARIO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(CLIENTE_COD_CLIENTE)
    REFERENCES CLIENTE(COD_CLIENTE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(FPAGAMENTO_COD_FPAGAMENTO)
    REFERENCES FPAGAMENTO(COD_FPAGAMENTO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION);


CREATE INDEX VENDA_FKIndex1 ON VENDA (FUNCIONARIO_COD_FUNCIONARIO);
CREATE INDEX VENDA_FKIndex2 ON VENDA (CLIENTE_COD_CLIENTE);
CREATE INDEX VENDA_FKIndex3 ON VENDA (FPAGAMENTO_COD_FPAGAMENTO);



CREATE TABLE CPAGAR (
  COD_CPARGAR INTEGER  NOT NULL  ,
  FORNECEDOR_COD_FORNECEDOR INTEGER  NOT NULL  ,
  FPAGAMENTO_COD_FPAGAMENTO INTEGER  NOT NULL  ,
  COMPRA_COD_COMPRA INTEGER  NOT NULL  ,
  STATUS_CPAGAR CHAR(1)  NOT NULL  ,
  DATA_CADASTRO DATE  NOT NULL    ,
PRIMARY KEY(COD_CPARGAR)      ,
  FOREIGN KEY(COMPRA_COD_COMPRA)
    REFERENCES COMPRA(COD_COMPRA)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(FPAGAMENTO_COD_FPAGAMENTO)
    REFERENCES FPAGAMENTO(COD_FPAGAMENTO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(FORNECEDOR_COD_FORNECEDOR)
    REFERENCES FORNECEDOR(COD_FORNECEDOR)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION);


CREATE INDEX CPAGAR_FKIndex1 ON CPAGAR (COMPRA_COD_COMPRA);
CREATE INDEX CPAGAR_FKIndex2 ON CPAGAR (FPAGAMENTO_COD_FPAGAMENTO);
CREATE INDEX CPAGAR_FKIndex3 ON CPAGAR (FORNECEDOR_COD_FORNECEDOR);



CREATE TABLE CRECEBER (
  COD_CRECEBER INTEGER  NOT NULL  ,
  CLIENTE_COD_CLIENTE INTEGER  NOT NULL  ,
  FPAGAMENTO_COD_FPAGAMENTO INTEGER  NOT NULL  ,
  VENDA_COD_VENDA INTEGER  NOT NULL  ,
  STATUS_CRECEBER CHAR(1)  NOT NULL  ,
  DATA_CADASTRO DATE  NOT NULL    ,
PRIMARY KEY(COD_CRECEBER)      ,
  FOREIGN KEY(VENDA_COD_VENDA)
    REFERENCES VENDA(COD_VENDA)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(FPAGAMENTO_COD_FPAGAMENTO)
    REFERENCES FPAGAMENTO(COD_FPAGAMENTO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(CLIENTE_COD_CLIENTE)
    REFERENCES CLIENTE(COD_CLIENTE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION);


CREATE INDEX CRECEBER_FKIndex1 ON CRECEBER (VENDA_COD_VENDA);
CREATE INDEX CRECEBER_FKIndex2 ON CRECEBER (FPAGAMENTO_COD_FPAGAMENTO);
CREATE INDEX CRECEBER_FKIndex3 ON CRECEBER (CLIENTE_COD_CLIENTE);



CREATE TABLE PARCELA_RECEBER (
  COD_PR INTEGER  NOT NULL  ,
  CRECEBER_COD_CRECEBER INTEGER  NOT NULL  ,
  NUMERO_PR NUMERIC  NOT NULL  ,
  VALOR_TOTAL NUMERIC  NOT NULL  ,
  VALOR_QUITADO NUMERIC  NOT NULL  ,
  DESCONTO NUMERIC    ,
  VALOR_PENDENTE NUMERIC  NOT NULL  ,
  VENCIMENTO DATE  NOT NULL  ,
  DATA_CADASTRO DATE  NOT NULL  ,
  STATUS_PR CHAR(1)  NOT NULL    ,
PRIMARY KEY(COD_PR)  ,
  FOREIGN KEY(CRECEBER_COD_CRECEBER)
    REFERENCES CRECEBER(COD_CRECEBER)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION);


CREATE INDEX PARCELA_RECEBER_FKIndex1 ON PARCELA_RECEBER (CRECEBER_COD_CRECEBER);



CREATE TABLE PARCELA_PAGAR (
  COD_PP INTEGER  NOT NULL  ,
  CPAGAR_COD_CPARGAR INTEGER  NOT NULL  ,
  NUMERO_PP NUMERIC  NOT NULL  ,
  VALOR_TOTAL NUMERIC  NOT NULL  ,
  VALOR_QUITADO NUMERIC  NOT NULL  ,
  VALOR_PENDENTE NUMERIC  NOT NULL  ,
  VENCIMENTO DATE  NOT NULL  ,
  DATA_CADASTRO DATE  NOT NULL  ,
  STATUS_PP CHAR(1)  NOT NULL    ,
PRIMARY KEY(COD_PP)  ,
  FOREIGN KEY(CPAGAR_COD_CPARGAR)
    REFERENCES CPAGAR(COD_CPARGAR)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION);


CREATE INDEX PARCELA_PAGAR_FKIndex1 ON PARCELA_PAGAR (CPAGAR_COD_CPARGAR);



CREATE TABLE IVENDA (
  COD_IVENDA INTEGER  NOT NULL  ,
  PRODUTO_COD_PRODUTO INTEGER  NOT NULL  ,
  VENDA_COD_VENDA INTEGER  NOT NULL  ,
  QUANTIDADE NUMERIC  NOT NULL  ,
  VALOR_UNITARIO NUMERIC  NOT NULL  ,
  DESCONTO NUMERIC  NOT NULL    ,
PRIMARY KEY(COD_IVENDA)    ,
  FOREIGN KEY(VENDA_COD_VENDA)
    REFERENCES VENDA(COD_VENDA)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(PRODUTO_COD_PRODUTO)
    REFERENCES PRODUTO(COD_PRODUTO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION);


CREATE INDEX IVENDA_FKIndex1 ON IVENDA (VENDA_COD_VENDA);
CREATE INDEX IVENDA_FKIndex2 ON IVENDA (PRODUTO_COD_PRODUTO);



CREATE TABLE RECEBIMENTO (
  COD_RECEBIMENTO INTEGER  NOT NULL  ,
  CHEQUE_COD_CHEQUE INTEGER  NOT NULL  ,
  PARCELA_RECEBER_COD_PR INTEGER  NOT NULL  ,
  VALOR NUMERIC  NOT NULL  ,
  DATA_CADASTRO DATE  NOT NULL    ,
PRIMARY KEY(COD_RECEBIMENTO)    ,
  FOREIGN KEY(PARCELA_RECEBER_COD_PR)
    REFERENCES PARCELA_RECEBER(COD_PR)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(CHEQUE_COD_CHEQUE)
    REFERENCES CHEQUE(COD_CHEQUE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION);


CREATE INDEX RECEBIMENTO_FKIndex1 ON RECEBIMENTO (PARCELA_RECEBER_COD_PR);
CREATE INDEX RECEBIMENTO_FKIndex2 ON RECEBIMENTO (CHEQUE_COD_CHEQUE);



CREATE TABLE PAGAMENTO (
  COD_PAGAMENTO INTEGER  NOT NULL  ,
  PARCELA_PAGAR_COD_PP INTEGER  NOT NULL  ,
  VALOR NUMERIC  NOT NULL  ,
  DATA_CADASTRO DATE  NOT NULL    ,
PRIMARY KEY(COD_PAGAMENTO)  ,
  FOREIGN KEY(PARCELA_PAGAR_COD_PP)
    REFERENCES PARCELA_PAGAR(COD_PP)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION);


CREATE INDEX PAGAMENTO_FKIndex1 ON PAGAMENTO (PARCELA_PAGAR_COD_PP);



CREATE TABLE MOVIMENTO_CAIXA (
  COD_ICAIXA INTEGER  NOT NULL  ,
  CAIXA_COD_CAIXA INTEGER  NOT NULL  ,
  RECEBIMENTO_COD_RECEBIMENTO INTEGER  NOT NULL  ,
  PAGAMENTO_COD_PAGAMENTO INTEGER  NOT NULL  ,
  DESCRICAO VARCHAR(80)  NOT NULL  ,
  NATUREZA CHAR(1)  NOT NULL  ,
  VALOR NUMERIC  NOT NULL  ,
  DATA_CADASTRO DATE  NOT NULL    ,
PRIMARY KEY(COD_ICAIXA)      ,
  FOREIGN KEY(PAGAMENTO_COD_PAGAMENTO)
    REFERENCES PAGAMENTO(COD_PAGAMENTO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(RECEBIMENTO_COD_RECEBIMENTO)
    REFERENCES RECEBIMENTO(COD_RECEBIMENTO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(CAIXA_COD_CAIXA)
    REFERENCES CAIXA(COD_CAIXA)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION);


CREATE INDEX ICAIXA_FKIndex1 ON MOVIMENTO_CAIXA (PAGAMENTO_COD_PAGAMENTO);
CREATE INDEX ICAIXA_FKIndex2 ON MOVIMENTO_CAIXA (RECEBIMENTO_COD_RECEBIMENTO);
CREATE INDEX ICAIXA_FKIndex3 ON MOVIMENTO_CAIXA (CAIXA_COD_CAIXA);




